"""add card back face fields

Revision ID: 025a705530bb
Revises: 
Create Date: 2026-03-06 16:22:43.068873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025a705530bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('image_back', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('back_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('back_type_line', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('back_oracle_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('back_mana_cost', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('back_mana_cost')
        batch_op.drop_column('back_oracle_text')
        batch_op.drop_column('back_type_line')
        batch_op.drop_column('back_name')
        batch_op.drop_column('image_back')
        batch_op.drop_column('layout')

    # ### end Alembic commands ###
